uploads = []
generated = []

[[outputs]]
id = "jCTXDtdLp7AedL96d-5aI"
uri = "file://deploy/DEPLOY.md"
type = "text"
title = "Инструкция по установке на VPS рег.ру"

[[outputs]]
id = "ANW1CzAtF7QCIMQEiT2-J"
uri = "file://deploy/DOMAIN.md"
type = "text"
title = "Подключение домена и HTTPS"
